### ISSUE TITLE
Script error: Out of bounds get index '0' (on base: 'PackedInt32Array')

### ISSUE THREAD

**Issue by Calinou** [gongpha/gdQmapbsp#1]
**OS:** Fedora 37
**Godot version:** 4.0.2.stable

My settings:

![image](https://user-images.githubusercontent.com/180032/234912036-fbfb94d1-903d-4609-8417-1a2b24409a22.png)

Debugger output and local state:

![image](https://user-images.githubusercontent.com/180032/234912308-298e5f22-1670-4982-b2ae-45ce056be9bf.png)

I've tried this process without filling in the map source directory path, but I get the same error.

**Comment by gongpha** [comment]
I've seen the original Quake 1 paks are only pak0 and pak1. Where's the pak2 file come from ? Is it a mod or something ? I guess it contains no lump files and makes the error.

**Comment by Calinou** [comment]
> I've seen the original Quake 1 paks are only pak0 and pak1. Where's the pak2 file come from ? Is it a mod or something ? I guess it contains no lump files and makes the error.

It contains maps, I assume it's a PAK containing compiled maps from the GPL map sources: 
![image](https://user-images.githubusercontent.com/180032/234989085-e998865f-37e6-4f7c-8c9a-37244a274eaa.png)

**Comment by gongpha** [comment]
> What's strange is that they're all displayed as "no map file", despite me specifying a folder that contains .map sources for all maps.

I tried using the map sources like yours (https://github.com/fzwoch/quake_map_source). And it seems like the playable map sources are still found. Have you tried scrolling down yet ?

![Godot_v4 0 2-stable_win64_xNJ1AN8Y3s](https://user-images.githubusercontent.com/13400398/235131893-83100420-f647-47a3-babb-bf93938f8ebe.png)

Even adding my own `pak2.pak` which contains only BSP files like yours after being fixed by dd93db43d9e04462a42f0e515340d51c90720d1b. It is still found.

**Comment by Calinou** [comment]
I've tested https://github.com/gongpha/gdQmapbsp/commit/dd93db43d9e04462a42f0e515340d51c90720d1b on 4.0.2, I still can't find the map files:

![image](https://github.com/gongpha/gdQmapbsp/assets/180032/c1ebb44d-179f-4f48-a3eb-fd0b54fd6acb)

**Comment by gongpha** [comment]
Can you try unchecking the "Convert MAP filenames to UPPERCASE on load" checkbox ? It will stop the filenames from being converted to uppercase.

I made this option because some map sources were published using uppercase names. AFAIK, Linux filenames are case-sensitive unlike Windows (11) which seems not to care about being case-sensitive.

![image](https://github.com/gongpha/gdQmapbsp/assets/13400398/4f1e8422-44e0-44d1-b99a-1935721a6919)
